# Generated by Django 3.0.4 on 2020-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200724_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release',
            field=models.IntegerField(),
        ),
    ]
