# Generated by Django 3.0.4 on 2020-07-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200728_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
