# Generated by Django 3.0.4 on 2020-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_image', models.ImageField(null=True, upload_to='profilesImage/', verbose_name='UserImage')),
                ('first_name', models.CharField(max_length=150, verbose_name='Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('birthday', models.DateField(default='01.01.1999', verbose_name='Date of birthday')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
