# Generated by Django 3.0.4 on 2020-07-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileUser',
        ),
    ]
