# Generated by Django 3.0.4 on 2020-07-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200730_1111'),
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0006_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
