# Generated by Django 3.0.4 on 2020-07-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20200730_1111'),
        ('user', '0007_auto_20200730_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
