# Generated by Django 3.0.4 on 2020-07-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200730_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
