# Generated by Django 3.0.4 on 2020-07-30 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelManagers(
            name='profiles',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
